[package]
name = "ntripping"
version = "1.1.1-alpha.1"
authors = ["Swift Navigation <dev@swiftnav.com>"]
edition = "2018"
publish = false

[dependencies]
curl = "^0.4.44"
clap = { version = "3", features = ["derive"] }
chrono = "0.4"

[build-dependencies]
vergen = "3"
