[package]
name = "ntripping"
version = "1.0.6-alpha.0"
authors = ["Swift Navigation <dev@swiftnav.com>"]
edition = "2018"
publish = false

[dependencies]
curl = "0.4"
curl-sys = "0.4"
structopt = "0.3"
chrono = "0.4"

[build-dependencies]
vergen = "3"
