[tasks.zip-release-binary-for-target]
description = "Zips up the release binary, README, and license(s)"
category = "Publish"
condition = { env_set = [
  "CARGO_MAKE_RELEASE_FLOW_TARGET",
  "CARGO_MAKE_PROJECT_NAME",
  "CARGO_MAKE_PROJECT_VERSION",
  "CARGO_MAKE_BINARY_EXECUTABLE_NAME",
], env_true = ["CARGO_MAKE_CI"] }
env = { "OUTPUT_NAME" = "${CARGO_MAKE_PROJECT_NAME}-${CARGO_MAKE_PROJECT_VERSION}-${CARGO_MAKE_RELEASE_FLOW_TARGET}" }
script_runner = "@duckscript"
script = '''
OUTPUT_NAME = get_env OUTPUT_NAME
CARGO_MAKE_RELEASE_FLOW_TARGET = get_env CARGO_MAKE_RELEASE_FLOW_TARGET
CARGO_MAKE_BINARY_EXECUTABLE_NAME = get_env CARGO_MAKE_BINARY_EXECUTABLE_NAME
mkdir ${OUTPUT_NAME}
cp target/${CARGO_MAKE_RELEASE_FLOW_TARGET}/release/${CARGO_MAKE_BINARY_EXECUTABLE_NAME} ${OUTPUT_NAME}/
cp README.md ${OUTPUT_NAME}/
glob_cp LICENSE* ${OUTPUT_NAME}/
exec --fail-on-error zip -r ${OUTPUT_NAME}.zip ${OUTPUT_NAME}
'''
