allow-branch = ["master"]
sign-commit = false
sign-tag = false
push-remote = "origin"
release = true
publish = false
verify = true
push = true
push-options = []
dev-version-ext = "alpha.0"
dev-version = false
shared-version = false
consolidate-commits = false
consolidate-pushes = true
pre-release-replacements = []
post-release-replacements = []
pre-release-commit-message = "release: {{crate_name}}: version {{version}}"
tag-message = "ntripping version {{tag_name}}"
tag-prefix = ""
tag-name = "{{prefix}}v{{version}}"
tag = true
enable-features = []
enable-all-features = false
dependent-version = "fix"
