release = true
publish = false
push = true
consolidate-commits = false
pre-release-commit-message = "release: {{crate_name}}: version {{version}}"
tag-message = "ntripping version {{tag_name}}"
tag-prefix = ""
tag-name = "{{prefix}}v{{version}}"
