name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  lint:
    name: Format and lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: Format Check
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        name: Lint
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings
  test:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: Run tests
        with:
          command: test
          args: --all-features --all-targets
  build:
    name: Build binaries
    needs:
      - lint
      - test
    strategy:
      matrix:
        os: [windows-2019, macos-11, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
        with:
          version: 0.32.12
      - name: Run CI
        run: cargo make ci-flow
