name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            binary_target: x86_64-unknown-linux-musl
          - os: windows-2019
            binary_target: x86_64-pc-windows-msvc
          - os: macos-11
            binary_target: x86_64-apple-darwin
    steps:
    - name: Install musl tools
      if: matrix.os == 'ubuntu-18.04'
      run: sudo apt-get install musl-tools
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install rust for target ${{ matrix.binary_target }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-${{ matrix.binary_target }}
        profile: minimal
    - uses: davidB/rust-cargo-make@v1
    - name: Get tag
      id: get_tag
      shell: bash
      run: echo ::set-output name=tag::${GITHUB_REF##refs/tags/}
    - name: Build Binary
      shell: bash
      run: |
        cargo make \
          --env CARGO_MAKE_RELEASE_FLOW_TARGET=${{ matrix.binary_target }} \
          --env CARGO_MAKE_PROJECT_VERSION=${{ steps.get_tag.outputs.tag }} \
          zip-release-ci-flow
    - name: Upload Binaries
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.zip'
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
  
  post-build:
    name: Post Build
    runs-on: ubuntu-18.04
    needs: [ build ]
    steps:
      - name: Get tag
        id: get_tag
        shell: bash
        run: echo ::set-output name=tag::${GITHUB_REF##refs/tags/}
      - name: Hook into package registry
        uses: swift-nav/swift-cli-publisher@v2
        env:
          DL_LINUX: "ntripping-${{ steps.get_tag.outputs.tag }}-x86_64-unknown-linux-musl.zip"
          DL_MAC: "ntripping-${{ steps.get_tag.outputs.tag }}-x86_64-apple-darwin.zip"
          DL_WIN: "ntripping-${{ steps.get_tag.outputs.tag }}-x86_64-pc-windows-msvc.zip"
          TOOLS: "ntripping"
        with:
          token: ${{ secrets.GH_TOKEN }}
          gh-name: ${{ secrets.GH_NAME }}
          gh-email: ${{ secrets.GH_EMAIL }}
